/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GenUiRouteImport } from './routes/gen-ui'
import { Route as IndexRouteImport } from './routes/index'

const GenUiRoute = GenUiRouteImport.update({
  id: '/gen-ui',
  path: '/gen-ui',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gen-ui': typeof GenUiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gen-ui': typeof GenUiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gen-ui': typeof GenUiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gen-ui'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gen-ui'
  id: '__root__' | '/' | '/gen-ui'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenUiRoute: typeof GenUiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/gen-ui': {
      id: '/gen-ui'
      path: '/gen-ui'
      fullPath: '/gen-ui'
      preLoaderRoute: typeof GenUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenUiRoute: GenUiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
